### PR TITLE
Update fire-tv-recommendations-best-practices.md

### PR DESCRIPTION
**Pull request by esaba**
Fixed minor typos.

### CODE REVIEW

**Comment by tomjoht** [comment]
Thanks for identifying and fixing the typo.

**Comment by tomjoht** [comment]
By the way, I enjoyed reading your blog post on AFTV News re the recommendations feature.

**Comment by esaba** [comment]
Thanks Tom! I wasn't sure if you guys were open to outside edits. Now that I know you are, I'll try contributing here and there for your consideration. (I think I came across an incorrect link somewhere that I'll go back and try to find.) Needless to say, I'm a big fan of the Fire TV and I'm happy to help where I can.

I'm glad you enjoyed my post! The recommendations feature is a great addition to the UI. I hope more developers and content providers use it.

**Comment by tomjoht** [comment]
We're definitely open to outside edits. This is one reason we put the Fire TV docs on GitHub. Feel free to make edits or other contributions as needed. You're definitely one of Fire TV's biggest community mavens, and I do check out aftvnews pretty often. You have some great, often prescient insights. 

You can also just log issues on the [Issues tab](https://github.com/amzn/appstore-alexa-docs/issues). For example, if you think a tutorial or article is needed, but one doesn't exist and you don't have the info or time to write it, log it there and I'll try to add it.

**Comment by esaba** [comment]
Thanks and will do! My insights are being influenced more and more by mutual friends, so I can't take full credit. I'm lucky to have friends who help me find needles* in the haystack so I'm not just guessing blindly with stark* outcomes.

**Pull request merged**
